### PR TITLE
[WIP] updated ubi image to latest. Issue no 2165

### PR DESCRIPTION
**Pull request by KNishit92**
Points Covered in the PR - 
1. Updated the ubi8  level to the latest version.

### CODE REVIEW

**Comment by KNishit92** [comment]
@NDaffernIBM  please let me know if anything else is required from the changes POV. Should we allow the user to choose the level via some automated process ? If so, what should be the frequency of such level change ? 
What are the parameters required for affirming whether the chosen level is compatible with the security related guidelines.

**Comment by NDaffernIBM** [comment]
So for your last question - On the page where you got this image from there is also a security tab for each image which defines the CVEs for that image i.e (https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.4-210&push_date=1632220161000) - That would be a good reference point to determine if there are vulnerabilities in the current image 

I think the changes you've made here are fine and we can merge them although I do agree by taking this approach we would need to be monitoring and updating this value periodically 

The other options could be 
1. Just use the latest tag (Good because most likely we get something that is secure, Bad because we won't have tested it although the risk of something going wrong here is probably minimal - We would also need to update the image when ubi8 becomes ubi9)
2. As mentioned in the original issue template the ubi version and possibly have the user pass it in at (Good because we don't need to worry about the version, Bad because it reduces usability)

**Comment by KNishit92** [comment]
Tested on Single Instance. and native HA QMs with persistent vol claim. The latest version seemingly doesn't have any unapplied Critical or Important security updates.

**Review by NDaffernIBM — APPROVED** [review]
Looks good to me

**Pull request merged**
